name: learning_first_github_actions
run-name: ${{ github.actor }} is learning Github Actions

on: 
  push: 
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello worlddd"
        shell: bash


  
